language: cpp
sudo: required
dist: yakkety
script: "make"
notifications:
    email:
        on_success: always
        on_failure: always
        on_start: always
addons:
    apt:
        sources:
            - sourceline: 'deb http://us.archive.ubuntu.com/ubuntu main'
        packages: gcc

       
before_install:
    - sudo apt-get update -qq

before_script:
    - g++ --version
    - gcc --version
    - make --version

