language: cpp
sudo: required
dist: yakkety
script: "make"
notifications:
    email:
        on_success: always
        on_failure: always
        on_startup: always

before_script:
    - ls -alF
    - g++ --version
    - make --version
    - mkdir bin obj || true
