language: cpp
sudo: required
dist: yakkety
script: "make"
notifications:
    email:
        on_success: always
        on_failure: always
        on_start: always
        packages: gcc

before_script:
    - wget https://github.com/gcc-mirror/gcc/archive/gcc-6_3_0-release.zip -O gcc.zip
    - mkdir gcc
    - unzip gcc.zip -d gcc
    - ls gcc
    - exit 1
    - g++ --version
    - gcc --version
    - make --version

