language: cpp
sudo: required
dist: yakkety
script: "make"
notifications:
    email:
        on_success: always
        on_failure: always
        on_start: always
        packages: gcc

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++

after_install:
    - :

before_script:
    - g++ --version
    - gcc --version
    - make --version

